on:
  push:
    branches: [main, stage, dev]
  pull_request:
    branches: [main, stage, dev]
  workflow_dispatch:

name: Check Package 📦

jobs:
  check:
    name: Release (from ramnog)
    uses: hta-pharma/ramnog/.github/workflows/Release-package.yaml@feature/workflows_final


  
